// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwcbta-WjdbdXgSveyEBNFkYZ8hQ0BKVg',
    appId: '1:233821184424:web:7280305e2ccc6e5dd77d9d',
    messagingSenderId: '233821184424',
    projectId: 'abhiman-assignment',
    authDomain: 'abhiman-assignment.firebaseapp.com',
    storageBucket: 'abhiman-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDKMUME4se9bxPYN9VD3OfTKvnfBjvp2c',
    appId: '1:233821184424:android:482bd4cedec8b7c0d77d9d',
    messagingSenderId: '233821184424',
    projectId: 'abhiman-assignment',
    storageBucket: 'abhiman-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZqNwxj_5rm5_MpJD2yigKZ4Woo-DPiXY',
    appId: '1:233821184424:ios:0d74470c5c5954f8d77d9d',
    messagingSenderId: '233821184424',
    projectId: 'abhiman-assignment',
    storageBucket: 'abhiman-assignment.appspot.com',
    iosBundleId: 'com.example.abhimanAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZqNwxj_5rm5_MpJD2yigKZ4Woo-DPiXY',
    appId: '1:233821184424:ios:0d74470c5c5954f8d77d9d',
    messagingSenderId: '233821184424',
    projectId: 'abhiman-assignment',
    storageBucket: 'abhiman-assignment.appspot.com',
    iosBundleId: 'com.example.abhimanAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwcbta-WjdbdXgSveyEBNFkYZ8hQ0BKVg',
    appId: '1:233821184424:web:909bf8f1c81fc6b1d77d9d',
    messagingSenderId: '233821184424',
    projectId: 'abhiman-assignment',
    authDomain: 'abhiman-assignment.firebaseapp.com',
    storageBucket: 'abhiman-assignment.appspot.com',
  );
}
